seed: ../results_MultiXrank/seed_files/seeds_25.txt
self_loops: 0
r: 0.7
eta: [1, 0]
lamb:
    - [0.5,0.5]
    - [0.5,0.5]
multiplex:
    RareX_layer:
        layers:
            - ../network/multilayer/RareX_layer.tsv
        delta: 0
        graph_type: [01]
        tau: [1]
    Orphanet_layer:
        layers:
            - ../network/multilayer/Orphanet_layer.tsv
        delta: 0
        graph_type: [01]
        tau: [1]
bipartite:
    ../network/bipartite/bipartite_RareX_Orpha_diseases.tsv: {'source': 'RareX_layer', 'target': 'Orphanet_layer', graph_type: 00}
