seed: seed_files_DiseaseDisease_Phenotype/seeds_1.txt
self_loops: 0
r: 0.7
eta: [1, 0]
lamb:
    - [0.5,0.5]
    - [0.5,0.5]
multiplex:
    Rare_X_layer:
        layers:
            - ../network/multiplex/RARE_X/RARE_X_layer.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
    Orpha_layer:
        layers:
            - ../network/multiplex/Orpha/DiseaseDisease_Phenotype.tsv
        delta: 0
        graph_type: [00]
        tau: [1]
bipartite:
    ../network/bipartite/bipartite_RARE_X_orpha_diseases.tsv: {'source': 'Rare_X_layer', 'target': 'Orpha_layer', graph_type: 00}
